---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          VALIDATE_GROOVY: false
          VALIDATE_KOTLIN: false
          VALIDATE_KOTLIN_ANDROID: false
          VALIDATE_HTML: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_BASH: false
