---
name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          channel: 'stable'
      - run: flutter --version
      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze --fatal-infos
      - name: Run tests
        run: flutter test
      - name: Run Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_CPP: false
          VALIDATE_GROOVY: false
          VALIDATE_KOTLIN: false
          VALIDATE_KOTLIN_ANDROID: false
          VALIDATE_HTML: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_BASH: false
